Repository currocam/HMMERutils, pull requests merged in 2022-11, with the labels that each got.

#5 feat: add extract_from_hmmer function
  DESCRIPTION
  NAMESPACE
  R/add_physicochemical_properties_to_HMMER_tbl.R
  R/add_sequences_to_hmmer_tbl.R
  R/add_taxa_to_hmmer_tbl.R
  R/annotate_with_ncbi.R
  R/extract_from_hmmer.R
  R/globals.R
  R/search_hmmsearch.R
  R/utils-pipe.R
  inst/extdata/data_short.rds
  man/add_AAStringSet_to_tbl.Rd
  man/add_physicochemical_properties_to_HMMER_tbl.Rd
  man/add_sequences_to_hmmer_tbl.Rd
  man/add_taxa_to_hmmer_tbl.Rd
  man/annotate_with_NCBI_taxid.Rd
  man/extract_from_hmmer.Rd
  man/pipe.Rd
  man/search_hmmsearch.Rd
  renv.lock
  tests/testthat/_snaps/extract_from_hmmer.md
  tests/testthat/test-extract_from_hmmer.R
  vignettes/HMMERutils.Rmd
Labels: enhancement

#7 fix: Ubuntu Set BiocVersion
  .github/workflows/check-bioc.yml
  DESCRIPTION
  renv.lock
Labels: bug

#13 feat: filter hmmer function
  DESCRIPTION
  NAMESPACE
  R/filter_hmmer.R
  man/filter_hmmer.Rd
  tests/testthat/test-filter_hmmer.R
Labels: enhancement

#20 [BUG] Extract domains columns incorrect type
  R/extract_from_hmmer.R
  renv.lock
Labels: bug

#22 Update Docs + Windows Issue
  vignettes/HMMERutils.Rmd
Labels: bug, documentation

#24 Warnings + Notes Workflow fix
  DESCRIPTION
  R/add_physicochemical_properties_to_HMMER_tbl.R
  R/add_sequences_to_hmmer_tbl.R
  R/annotate_with_ncbi.R
  R/data.R
  R/extract_from_hmmer.R
  R/read_hmmer_from_json.R
  R/utils-pipe.R
  R/utils.R
  inst/extdata/phmmer_2abl_no_sequences.xml
  man/add_sequences_to_hmmer_tbl.Rd
  man/hmmscan_2abl.Rd
  man/phmmer_2abl.Rd
  man/pipe.Rd
  man/read_hmmer_from_json.Rd
Labels: documentation

#25 Fix "Warnings + Notes Workflow fix"
  DESCRIPTION
  R/add_physicochemical_properties_to_HMMER_tbl.R
  R/add_sequences_to_hmmer_tbl.R
  R/data.R
  R/hmmer_evalues_cleveland_dot_plot.R
  R/pairwise_alignment.R
  R/parse_fasta_header.R
  R/read_hmmer_from_json.R
  R/search_hmmscan.R
  R/search_hmmsearch.R
  R/search_phmmer.R
  R/utils-pipe.R
  inst/extdata/phmmer_2abl.xml
  inst/extdata/phmmer_2abl_no_sequences.xml
  man/add_physicochemical_properties_to_HMMER_tbl.Rd
  man/add_sequences_to_hmmer_tbl.Rd
  man/pairwise_alignment_sequence_identity.Rd
  man/pairwise_sequence_identity_histogram.Rd
  man/parse_fasta_headers.Rd
  man/phmmer_2abl.Rd
  man/read_hmmer_from_json.Rd
  man/search_hmmscan.Rd
  man/search_hmmsearch.Rd
  man/search_phmmer.Rd
Labels: documentation
